name: Integration

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.ref_name }}-${{
    github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  PACKAGE_NAME: ubo-app
  PYTHON_VERSION: '3.11'

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-0

      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true

      - name: Install dependencies
        run: poetry install --extras=dev --with dev

      - name: Lint
        run: poetry run poe lint

      - name: Create stub files
        run: poetry run pyright --createstub kivy

      - name: Type Check
        run: poetry run poe typecheck

      - name: build package
        run: poetry build

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/*.whl
          if-no-files-found: error

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: dist/*.tar.gz
          if-no-files-found: error
